### ISSUE TITLE
Partials mainMenu to theme

### ISSUE THREAD

**Issue by johnbrett** [hadronjs/hadron#13]
I was trying to create a landscape theme like so:

![image](https://cloud.githubusercontent.com/assets/4015939/3272886/ae5147c2-f31d-11e3-937d-f97996be48f3.png)

But I came across the mainMenu partial (app/views/partials/mainMenu.jade), which is part of the app, as opposed to the Nodus theme. Is the easiest way to use this in the theme to have mainMenu made as part of the themes (I can try a PR), or is there a way to reuse the partial in the theme logic? I don't think I can reference settings.menu in my theme??

**Comment by mariocasciaro** [comment]
Yes you can reference the view in the main app. The asset manager emulates the behavior of Scatter, it does that by assembling all the views (and other assets) of every particle in the same dir. In your theme just reference the view like that: `include partials/mainMenu`, it should work.

**Comment by johnbrett** [comment]
Hey Mario, thanks for the quick response, I see how to customise the main menu, surprised how easy it is in fact! Going to close this.
