### ISSUE TITLE
Adding settings

### ISSUE THREAD

**Issue by johnbrett** [hadronjs/hadron#14]
Hey Mario,

Was looking at adding a configurable banner image for the theme I'm making. But I'm having trouble saving the new setting.

I've added to app/data/models/Settings.js:

```
website: {
    title: {
      type: String,
      required: true
    },
    headline: String,
    bannerImage: String // <-- new setting added
  }
```

and to app/views/clientTemplates/admin/websiteSettings.jade

```
div.form-group(ng-class="{'has-error': hasError('website.bannerImage')}")
  label.control-label(for="bannerImage") Blog Banner Image
  input.form-control(name="bannerImage", ng-model="settings.website.bannerImage", placeholder="Add banner image...")
```

The form displays just fine, but won't save the new data, but does save the existing forms. I thought extending the Settings model would be all to enable persisting the setting, am I missing something else to allow saving it?

**Comment by mariocasciaro** [comment]
Hey John, did you include also a new angular controller for the new
settings page?

**Comment by johnbrett** [comment]
Hey Mario, I've the update banner image working, but I had to update hadron's own Settings model in app/data/models/Settings.js. Is there a way to extend the settings model from my theme with mini model, or would I have to make a PR for hadron to support a bannerImage url by default?

**Comment by mariocasciaro** [comment]
You can extend the model from your plugin. Look at this: https://github.com/hadronjs/hadron-disqus/blob/master/lib/data/models/Settings.js
You will also need to specify that your particle extends Hadron, for an example: https://github.com/hadronjs/hadron-disqus/blob/master/lib/particle.json

For knowing more about particle extension:
https://github.com/mariocasciaro/scatter/wiki/Guide#extend-and-override-modules

**Comment by johnbrett** [comment]
That was exactly what I was looking for, cheers!
