### ISSUE TITLE
Error when pushing to heroku

### ISSUE THREAD

**Issue by LemonScript** [hadronjs/hadron#15]
Hi,

After pushing my hadron app to heroku for the first time i received this error: "Error: Failed to lookup view "errors/default" in views directory "/app/generated/views" at Function.app.render (/app/node_modules/express/lib/application.js:493:17) at ServerResponse.res.render (/app/node_modules/express/lib/response.js:798:7) at /app/node_modules/particles-express/lib/express/middleware/errors.js:33:17 at Object.cb [as oncomplete](fs.js:168:19)". I have made no backend changes to the code so I am unsure of why this error has occurred.

Heroku log states: "ERROR particles/express: There was an error while handling the request
"

thanks, jacob

**Comment by mariocasciaro** [comment]
Hi, are you committing the `generated` directory into git? Otherwise you need to run `gulp build` on the server. Also make sure to run `gulp install` on the server anyway, because it is needed to initialize the db.

**Comment by LemonScript** [comment]
Yes, the generated file is included in the commit

**Comment by mariocasciaro** [comment]
Did you check if the file was actually copied on the server?
Also, have you made any changes to the config?

**Comment by LemonScript** [comment]
Thanks for the help, i realised that i had made some changes to some of the files in the generated folder, using gulp build on the server resolved it!

**Comment by mariocasciaro** [comment]
No problem, just give a shout if you get stuck in any other problem.

**Comment by LemonScript** [comment]
I have adapted the _layout.jade, index.jade and posts/view.jade files, how could i use these in the final build? would i have to add them to the 'themes" folder?, thanks

**Comment by mariocasciaro** [comment]
Yes, just add them to the themes folder  and they should be picked up the next time you run `gulp build`

**Comment by LemonScript** [comment]
Hi, i appreciate the help! Just wondering if you could help me out one last time? I decided to migrate to openshift due to some problems with the non-writable dynos on heroku. I built the application using the hadron-openshift seed. When i call gulp build, the application builds the generated folder however the theme is not included, should i be doing something different on the openshift build?

**Comment by mariocasciaro** [comment]
No, the openshift build is just an orthogonal layer to the default seed, there shouldn't be any difference at all. When you say that the theme is not included do you mean that when you open the blog it doesn't show how it would with your theme applied? Is the problem happening only on openshift or also when you run the app locally?
If you could send me your project I can try give a look (confidentiality assured :P). contact [AT] mariocasciaro.me

**Comment by LemonScript** [comment]
its a weird one! When i ssh into my openshift application i can see my 'themes' folder inside of the app-root/runtime/repo folder. However, my theme doesnt seem to override the default theme. This problem occurs locally as well as on openshift. I have no problem with sending you my project :) do you have an email address i could send it to?

**Comment by mariocasciaro** [comment]
contact [AT] mariocasciaro.me

**Comment by LemonScript** [comment]
sent. Let me know if you havent received it

**Comment by mariocasciaro** [comment]
Yep got it :+1:

**Comment by mariocasciaro** [comment]
Looked at the code, you were actually right, the openshift seed made a change that broke your build. To fix it just add this parameters to `config/custom.json`:

```
  "containers": {
    "default": {
      "particles": ["${appRoot}/themes/*"]
    }
  }
```

This will tell Hadron where to look for the theme.
Let me know if it works.

**Comment by LemonScript** [comment]
Ah great! Its all [working](http://lemonscript-lemonscript.rhcloud.com/). Thanks! I will upload my adapted theme for others to use

**Comment by mariocasciaro** [comment]
Nice! This sounds like a great idea :+1:
