### ISSUE TITLE
Fails to start from Systemd

### ISSUE THREAD

**Issue by clickslide** [hadronjs/hadron#16]
Hello,

I'm trying to have my Hadron blog run as a service within SystemD on ArchLinux. However, the app does not start from the absolute path:

```
/usr/bin/node /home/user/hadron/app.js
```

That command fails to start the app. It gives the following warning:

```
WARN particles/scatter: No particles added
```

It seems the app will only start if run from within the installed directory. Do you have a work around for this?

**Comment by mariocasciaro** [comment]
Yes, you have to set the right working directory. You can do that by running:

```
cd /home/user/hadron
/usr/bin/node /home/user/hadron/app.js
```

**Comment by clickslide** [comment]
Unfortunately that does not work in ArchLinux. It seems the particles package depends on the directory from which it is started. Systemd requires everything to use absolute paths so the app never starts. The same problem occurs trying to use Forever with Systemd. 

Here is the Systemd service script I'm attempting to use.

```
[Unit]
Description=Blog

[Service]
WorkingDirectory=/home/user/hadron
ExecStart=/usr/bin/forever start /home/user/hadron/app.js
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by mariocasciaro** [comment]
You can try to start Hadron with the `cwd` option:

```
node /home/user/hadron/app --cwd=/home/user/hadron
```

**Comment by clickslide** [comment]
That worked, thanks
